export const SET_PROJECTS = "SET_PROJECTS";
export const SET_NEEDS_REVIEW = "SET_NEEDS_REVIEW";
export const SET_REQUIRES_FURTHER_SEQUENCING = "SET_REQUIRES_FURTHER_SEQUENCING";
export const SET_AWAITING_FURTHER_ACTION = "SET_AWAITING_FURTHER_ACTION";
export const SET_RECENT_DELIVERIES = "SET_RECENT_DELIVERIES";
export const SET_RECENT_RUNS = "SET_RECENT_RUNS";
